
version: 0.2

#$CODEBUILD_SRC_DIR is is a given env var

env:
  variables:
    customenvkey: "mycustomenvvalue"
phases:
  install:
    commands:
      - echo "install command..."
  pre_build:
    commands:
      - echo "pre-build commands..."
      - chmod a+x package.sh
  build:
    commands:
      - echo "build command..."
  post_build:
    commands:
      - ./package.sh
artifacts:
  files:
    - ./package/src.zip
    - ./deploy/**/*
  discard-paths: yes